package com.mirboard.domain.game.tichu.action;

public enum RejectionReason {
    NOT_IN_PLAYING_PHASE,
    NOT_YOUR_TURN,
    CARDS_NOT_OWNED,
    EMPTY_CARDS,
    INVALID_HAND,
    CANNOT_BEAT_CURRENT,
    DOG_MUST_BE_SOLO_LEAD,
    PASS_ON_LEAD_NOT_ALLOWED,
    WISH_NOT_FULFILLED,
    DRAGON_TRICK_RECIPIENT_MUST_BE_OPPONENT,
    DRAGON_GIVE_NOT_PERMITTED,
    NO_DRAGON_TRICK_TO_GIVE,
    TICHU_DECLARATION_TOO_LATE,
    GRAND_TICHU_DECLARATION_WRONG_PHASE,
    DUPLICATE_DECLARATION,
    INVALID_WISH_RANK,
    WISH_OUT_OF_CONTEXT,
    INVALID_STATE_FOR_ACTION
}
